/*! @file sample_code_func.h
 * @brief This file contains the automatically generated
 * configurations.
 *
 * @b COPYRIGHT
 * @n Silicon Laboratories Confidential
 * @n Copyright 2012 Silicon Laboratories, Inc.
 * @n http://www.silabs.com
 */

/***********************************************************
 ***********************************************************
 * THIS IS AN AUTOMATICALLY GENERATED CONFIGURATION FILE!
 *
 * DO NOT MODIFY!
 ***********************************************************
 ***********************************************************/

/* Begin Clean-Up */
#undef  EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION
#undef  EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC

#undef  EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE
#undef  EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#undef  EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE

#undef  EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS
#undef  EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS
#undef  EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ

#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE

#undef  EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24
#undef  EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16

#undef  EZCONFIG_ARRAY_DATA_PA_PWR_LVL

#undef  EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION
#undef  EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE

#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0

#undef  EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG
#undef  EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG
#undef  EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG
#undef  EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG
#undef  EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#undef  EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE
#undef  EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG

#undef  EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP
#undef  EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET

/* Clear Defaults */
#undef  EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT

#undef  EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT
#undef  EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT
/* End Clean-Up */


/* 316M66, 2FSK, 9k6 */
#ifdef RADIO_MULTIPLE_CONFIG_NO_1
#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION { \
0xAC, 0xEC, 0xE4, 0xA5, 0x0F, 0xD9, 0xFE, 0xB4, 0x42, 0x3A, 0x3F, 0x00, \
0x51, 0x7B, 0xFF, 0x58, 0xD4, 0x2D, 0x3D, 0xF4, 0xC2, 0x67, 0xD2, 0xDD, \
0xF2, 0x74, 0xA8, 0xFF, 0x6F, 0x20, 0x8B, 0xD3, 0x2A, 0x12, 0xC7, 0x51, \
0x1C, 0x80, 0x0F, 0x44, 0x44, 0x00, 0xBA, 0xB5, 0x13, 0x0D, 0xAC, 0x6D, \
0x48, 0xD9, 0xCC, 0xEB, 0xB7, 0x2A, 0x72, 0xCA, 0x82, 0x15, 0x50, 0xDA, \
0xC7, 0x00, 0xA4, 0xD3, 0x02, 0x12, 0xAE, 0x0D, 0xB7, 0xB6, 0xFB, 0x4E, \
0x14, 0xF7, 0x63, 0x55, 0xBD, 0xC6, 0x36, 0xB1, 0xE6, 0xF5, 0x44, 0x2B, \
0xAE, 0x0A, 0x60, 0xB1, 0x1E, 0xF7, 0x91, 0xAC, 0xE4, 0xDB, 0x2E, 0x89, \
0x5C, 0xD0, 0x7C, 0xFE, 0x9A, 0x50, 0xFD, 0x26, 0x0E, 0x10, 0x11, 0xA2, \
0x9D, 0x21, 0x38, 0x9A, 0xB9, 0xD9, 0x14, 0x2B, 0x0A, 0x74, 0x44, 0x00, \
0x00, 0x66, 0x5C, 0xD2, 0xAD, 0x08, 0xF7, 0xDB, 0x20, 0x0F, 0xC9, 0x5A, \
0x91, 0x54, 0xB4, 0x03, 0x63, 0x77, 0x3D, 0x31, 0xFC, 0x94, 0x43, 0x7B, \
0xB8, 0x53, 0x36, 0xDB, 0x68, 0xE3, 0x14, 0x82, 0x7C, 0xC9, 0x9B, 0x46, \
0x33, 0x35, 0x39, 0x8E, 0x75, 0x2B, 0x40, 0x7E, 0x7C, 0xB5, 0x94, 0x90, \
0xEC, 0x00, 0x4F, 0x02, 0x5C, 0xC9, 0x59, 0xCC, 0x83, 0xA3, 0xEE, 0x0B, \
0xA6, 0xE3, 0xB5, 0x57, 0xBD, 0x72, 0x86, 0x9B, 0xBF, 0xDA, 0x75, 0x4B, \
0x79, 0xAD, 0xD0, 0xA4, 0xC0, 0x55, 0x59, 0x84, 0x39, 0x89 }

#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC                 { 0x041D }

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE                          { 0x05 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE                       { 0x10 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE                    { 0x00 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE                     { 0x04 }

#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE                           { 0x00 }

#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT                0x01
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT                0x00
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT                     30000000L

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT                    0x04
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT                 0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT              0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT               0x04

#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT                    0x01
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT                    0x02
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT                    0x09
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT                    0x00

#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT                   0x2D
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT                   0xD4

#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT                        0x7F

#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT               0x02
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT                  0x40

#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT                 0x3C
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT               0x08
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT  0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT  0x00

#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT                    0x27
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT                   0x00

#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT         0x01
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT       0x1000



#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ         { EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE        { EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE     { EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE  { EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE   { EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24       { EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16       { EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_PA_PWR_LVL
#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL            { EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION
#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION   { EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE      { EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE     { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1  { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0  {  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE        { EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE         { EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG       { EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP
#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP   { EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET { EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT }
#endif

#define EZCONFIG_ARRAY_DATA { \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION,              \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC,          \
                            EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ,                    \
                            EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE,                   \
                            EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE,                \
                            EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE,             \
                            EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE,              \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE,                   \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24,                  \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16,                  \
                            EZCONFIG_ARRAY_DATA_PA_PWR_LVL,                       \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION,              \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE,                 \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE,                \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1, \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0, \
                            EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE,                   \
                            EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG,                  \
                            EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP,        \
                            EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET       \
                            }
#endif

/* 433M92, 2FSK, 9k6 */
#ifdef RADIO_MULTIPLE_CONFIG_NO_2
#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION { \
0xDD, 0xCA, 0x36, 0x9E, 0x76, 0x53, 0xDB, 0x5A, 0xFB, 0xC7, 0xAB, 0x79, \
0x39, 0x18, 0xC5, 0x84, 0x86, 0x06, 0x21, 0x4A, 0x0D, 0x48, 0x9D, 0x9B, \
0xCB, 0x76, 0x3F, 0x00, 0x13, 0x2A, 0xBC, 0x58, 0xA8, 0x24, 0xBF, 0xFF, \
0x6E, 0x4B, 0x96, 0xA8, 0x76, 0xC1, 0x9C, 0xE2, 0x39, 0x0C, 0x50, 0x6A, \
0x5D, 0xB3, 0xC7, 0xA8, 0x0B, 0x6F, 0x57, 0xC7, 0xF3, 0x04, 0x13, 0x39, \
0x0B, 0xE1, 0x49, 0xF2, 0xA3, 0x17, 0x76, 0xD1, 0x5C, 0x6B, 0x4E, 0x3B, \
0x98, 0xE4, 0x2D, 0x99, 0xB6, 0x12, 0xFD, 0x7F, 0xF7, 0x37, 0xA8, 0xC0, \
0xBC, 0x16, 0x48, 0x0B, 0x72, 0x05, 0xEA, 0x88, 0xBA, 0x63, 0x19, 0xF3, \
0xE9, 0x5E, 0x34, 0xC3, 0x9A, 0x9E, 0xE8, 0x6A, 0xEA, 0xF6, 0x1B, 0xC5, \
0xCC, 0xA9, 0x7B, 0x8D, 0x21, 0xA0, 0x40, 0xEA, 0xA3, 0xAD, 0x5A, 0xD2, \
0x15, 0x61, 0x01, 0x17, 0xFD, 0x7A, 0x32, 0x42, 0xEB, 0xEC, 0x35, 0x11, \
0x20, 0x4B, 0x55, 0x07, 0x3B, 0xB0, 0x79, 0x38, 0x5B, 0x79, 0xFB, 0xE0, \
0x95, 0xEA, 0x57, 0x07, 0xE0, 0x11, 0x0E, 0xF7, 0x12, 0x9C, 0x01, 0xEE, \
0x93, 0x06, 0x50, 0x51, 0xCE, 0x73, 0x06, 0x35, 0x52, 0xE1, 0x8E, 0x31, \
0x70, 0x8D, 0x2A, 0x7B, 0x11, 0x7B, 0x51, 0x5C, 0xDA, 0x1C, 0xBF, 0x69, \
0x09, 0x4D, 0xB5, 0xB0, 0xE6, 0xFF, 0x72, 0x8B, 0xE2, 0x78, 0x78, 0xA5, \
0x30, 0x70, 0xA8, 0x7A, 0x1E, 0x5F, 0xA1, 0xA4, 0xE6, 0x87 }

#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC                 { 0x88FE }

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE                          { 0x05 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE                       { 0x10 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE                    { 0x00 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE                     { 0x04 }

#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE                           { 0x00 }


#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT                0x01
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT                0x00
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT                     30000000L

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT                    0x04
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT                 0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT              0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT               0x04

#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT                    0x01
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT                    0x02
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT                    0x09
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT                    0x00

#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT                   0x2D
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT                   0xD4

#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT                        0x7F

#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT               0x02
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT                  0x40

#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT                 0x3C
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT               0x08
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT  0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT  0x00

#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT                    0x27
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT                   0x00

#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT         0x01
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT       0x1000



#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ         { EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE        { EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE     { EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE  { EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE   { EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24       { EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16       { EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_PA_PWR_LVL
#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL            { EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION
#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION   { EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE      { EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE     { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1  { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0  {  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE        { EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE         { EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG       { EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP
#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP   { EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET { EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT }
#endif

#define EZCONFIG_ARRAY_DATA { \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION,              \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC,          \
                            EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ,                    \
                            EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE,                   \
                            EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE,                \
                            EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE,             \
                            EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE,              \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE,                   \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24,                  \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16,                  \
                            EZCONFIG_ARRAY_DATA_PA_PWR_LVL,                       \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION,              \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE,                 \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE,                \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1, \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0, \
                            EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE,                   \
                            EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG,                  \
                            EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP,        \
                            EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET       \
                            }
#endif

/* 868M30, 2FSK, 9k6 */
#ifdef RADIO_MULTIPLE_CONFIG_NO_3
#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION { \
0xF2, 0x2B, 0x73, 0x43, 0x26, 0x7D, 0xD5, 0x9C, 0x48, 0xF6, 0xAB, 0xDC, \
0xE4, 0x0B, 0x6E, 0x12, 0x0B, 0x5F, 0xD0, 0xBF, 0x15, 0x2C, 0x99, 0xDE, \
0x4B, 0xE7, 0x55, 0x30, 0xC3, 0xAF, 0x4E, 0x65, 0x0C, 0x77, 0xC7, 0x00, \
0xEC, 0x40, 0xC6, 0x71, 0x40, 0xB5, 0x0B, 0x2E, 0xC1, 0x89, 0xF4, 0xA3, \
0x37, 0x73, 0x31, 0x16, 0xBB, 0x5F, 0x33, 0x04, 0x7C, 0x6E, 0x44, 0xB8, \
0xF5, 0xE5, 0x50, 0xE4, 0xDF, 0x90, 0x97, 0xD4, 0x08, 0x64, 0x94, 0xC9, \
0x67, 0xCA, 0xC1, 0x19, 0xD1, 0x4A, 0x7A, 0x95, 0x9F, 0x3E, 0xE4, 0x52, \
0x7D, 0xF0, 0x95, 0x93, 0xE5, 0x2E, 0x68, 0x7E, 0x88, 0xFD, 0xFE, 0xEF, \
0xFF, 0x6D, 0xEA, 0xA7, 0x0A, 0xAF, 0x21, 0x7A, 0x3A, 0x79, 0xD5, 0x4C, \
0x58, 0xE8, 0x85, 0x09, 0x34, 0xC3, 0x74, 0x14, 0x1A, 0x33, 0x87, 0x58, \
0xEB, 0x5C, 0x8D, 0xB4, 0x15, 0xCA, 0xE4, 0x13, 0xFF, 0x71, 0x06, 0xF5, \
0xD2, 0x2E, 0x2E, 0x04, 0x1E, 0x60, 0x4D, 0x5F, 0xBD, 0x70, 0x92, 0x6B, \
0x28, 0xFF, 0x8D, 0xAA, 0xDF, 0x71, 0xC3, 0x1C, 0xC6, 0x14, 0xC9, 0x68, \
0x32, 0xD2, 0x67, 0x1E, 0xD8, 0xAA, 0xA2, 0x3E, 0xB6, 0x80, 0x9F, 0x11, \
0xDA, 0xB2, 0x5D, 0xC8, 0x86, 0xA5, 0xEE, 0x1F, 0xDE, 0x8B, 0xD3, 0x70, \
0x38, 0xB1, 0x12, 0x65, 0xC6, 0xCE, 0x18, 0x58, 0x71, 0xF8, 0x1E, 0xF2, \
0x99, 0x7E, 0x7C, 0xAF, 0x17, 0x9D, 0x1D, 0xAF, 0x52, 0x06 }

#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC                 { 0x8A49 }

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE                          { 0x05 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE                       { 0x10 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE                    { 0x00 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE                     { 0x04 }

#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE                           { 0x00 }


#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT                0x01
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT                0x00
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT                     30000000L

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT                    0x04
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT                 0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT              0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT               0x04

#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT                    0x01
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT                    0x02
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT                    0x09
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT                    0x00

#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT                   0x2D
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT                   0xD4

#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT                        0x7F

#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT               0x02
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT                  0x40

#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT                 0x3C
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT               0x08
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT  0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT  0x00

#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT                    0x27
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT                   0x00

#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT         0x01
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT       0x1000



#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ         { EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE        { EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE     { EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE  { EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE   { EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24       { EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16       { EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_PA_PWR_LVL
#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL            { EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION
#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION   { EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE      { EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE     { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1  { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0  {  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE        { EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE         { EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG       { EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP
#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP   { EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET { EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT }
#endif

#define EZCONFIG_ARRAY_DATA { \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION,              \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC,          \
                            EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ,                    \
                            EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE,                   \
                            EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE,                \
                            EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE,             \
                            EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE,              \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE,                   \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24,                  \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16,                  \
                            EZCONFIG_ARRAY_DATA_PA_PWR_LVL,                       \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION,              \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE,                 \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE,                \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1, \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0, \
                            EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE,                   \
                            EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG,                  \
                            EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP,        \
                            EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET       \
                            }
#endif

/* 917M00, 2FSK, 9k6 */
#ifdef RADIO_MULTIPLE_CONFIG_NO_4
#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION { \
0x43, 0x8D, 0xAD, 0x59, 0xB8, 0x6A, 0xE9, 0x66, 0xDC, 0x9E, 0xA6, 0x8E, \
0x29, 0x4F, 0x5B, 0x3D, 0x58, 0x5D, 0x3A, 0xCA, 0x5B, 0xB5, 0x68, 0xAB, \
0x5F, 0xA2, 0xB6, 0xB5, 0x97, 0x81, 0x5B, 0xFA, 0x3A, 0x81, 0x4D, 0x04, \
0xC9, 0x9F, 0xC8, 0xF1, 0x6E, 0x4D, 0xE2, 0xC7, 0xEC, 0x20, 0x43, 0xE4, \
0x1A, 0x0C, 0xD2, 0x52, 0x6A, 0x25, 0xF6, 0x7A, 0x6E, 0xE0, 0x06, 0x1A, \
0xB9, 0x8E, 0x8E, 0x07, 0x0F, 0xCB, 0x50, 0x9D, 0x06, 0xED, 0x7F, 0x85, \
0xB9, 0xAF, 0x52, 0x2C, 0x01, 0x1D, 0x68, 0x1C, 0xC0, 0xCA, 0x18, 0x6B, \
0xE0, 0x2D, 0x15, 0x51, 0x6C, 0x92, 0x1F, 0x55, 0xDE, 0x0D, 0xBD, 0xB6, \
0xCF, 0x7C, 0x73, 0x33, 0x50, 0x64, 0x26, 0xB5, 0xBC, 0xF6, 0x19, 0x44, \
0x08, 0xAA, 0x74, 0x52, 0x59, 0x8D, 0xDB, 0x3C, 0x54, 0xC0, 0x78, 0x1F, \
0x1C, 0x98, 0x14, 0x45, 0x96, 0x61, 0x10, 0xD4, 0x53, 0x02, 0xC1, 0x4B, \
0xC7, 0xD1, 0x52, 0x08, 0x37, 0xBB, 0x6B, 0x57, 0x56, 0x3E, 0x4F, 0x15, \
0x03, 0x1F, 0x0F, 0xE5, 0x74, 0x2F, 0xF8, 0x4E, 0xBF, 0xE8, 0xDE, 0x1B, \
0x6F, 0x3A, 0xD0, 0xD5, 0xDF, 0x0E, 0x6D, 0x4E, 0x38, 0x8D, 0x9A, 0x21, \
0x6E, 0xAA, 0xBF, 0xDE, 0xB2, 0x66, 0xDC, 0x3F, 0xBD, 0x01, 0xA9, 0x5F, \
0xCA, 0x70, 0xB4, 0x3E, 0xCD, 0x28, 0x79, 0x46, 0x70, 0xBF, 0x80, 0x28, \
0x0E, 0xD6, 0xF1, 0x71, 0xF7, 0x1F, 0x52, 0x04, 0x0C, 0x3D }

#define EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC                 { 0xB31B }

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE                          { 0x05 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE                       { 0x10 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE                    { 0x00 }
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE                     { 0x04 }

#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE                           { 0x00 }


#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT                0x01
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT                0x00
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT                     30000000L

#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT                    0x04
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT                 0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT              0x00
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT               0x04

#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT                    0x01
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT                    0x02
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT                    0x09
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT                    0x00

#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT                   0x2D
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT                   0xD4

#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT                        0x7F

#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT               0x02
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT                  0x40

#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT                 0x3C
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT               0x08
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT               0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT  0x00
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT  0x00

#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT                    0x27
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT                     0x01
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT                   0x00

#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT         0x01
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT       0x1000



#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC
#error "This property must be defined!"
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS
#define EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS    { EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ
#define EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ         { EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE        { EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE     { EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE  { EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE
#define EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE   { EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE
#define EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE        { EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24       { EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16
#define EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16       { EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_PA_PWR_LVL
#define EZCONFIG_ARRAY_DATA_PA_PWR_LVL            { EZCONFIG_ARRAY_DATA_PA_PWR_LVL_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION
#define EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION   { EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE
#define EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE      { EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE     { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0   { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1  { EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0
#define EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0  {  EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG
#define EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG         { EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE        { EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE
#define EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE         { EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG
#define EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG       { EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP
#define EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP   { EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP_DEFAULT }
#endif

#ifndef EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET
#define EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET { EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET_DEFAULT }
#endif

#define EZCONFIG_ARRAY_DATA { \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION,              \
                            EZCONFIG_ARRAY_DATA_RADIO_CONFIGURATION_CRC,          \
                            EZCONFIG_ARRAY_DATA_RADIO_BOOT_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XTAL_OPTIONS,               \
                            EZCONFIG_ARRAY_DATA_RADIO_XO_FREQ,                    \
                            EZCONFIG_ARRAY_DATA_INT_CTL_ENABLE,                   \
                            EZCONFIG_ARRAY_DATA_INT_CTL_PH_ENABLE,                \
                            EZCONFIG_ARRAY_DATA_INT_CTL_MODEM_ENABLE,             \
                            EZCONFIG_ARRAY_DATA_INT_CTL_CHIP_ENABLE,              \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_A_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_B_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_C_MODE,                   \
                            EZCONFIG_ARRAY_DATA_FRR_CTL_D_MODE,                   \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_31_24,                  \
                            EZCONFIG_ARRAY_DATA_SYNC_BITS_23_16,                  \
                            EZCONFIG_ARRAY_DATA_PA_PWR_LVL,                       \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_MODULATION,              \
                            EZCONFIG_ARRAY_DATA_EZCONFIG_XO_TUNE,                 \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_INTE,                \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_2,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_1,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_FRAC_0,              \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_1, \
                            EZCONFIG_ARRAY_DATA_FREQ_CONTROL_CHANNEL_STEP_SIZE_0, \
                            EZCONFIG_ARRAY_DATA_GPIO0_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO1_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO2_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO3_PIN_CFG,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_NIRQ_MODE,                   \
                            EZCONFIG_ARRAY_DATA_GPIO_SDO_MODE,                    \
                            EZCONFIG_ARRAY_DATA_GPIO_GEN_CONFIG,                  \
                            EZCONFIG_ARRAY_DATA_RADIO_MODE_AFTER_POWER_UP,        \
                            EZCONFIG_ARRAY_DATA_RADIO_DELAY_CNT_AFTER_RESET       \
                            }
#endif

